#! /bin/sh

# Halt on error
set -e

# Backup the previous configuration
dpkg-divert --add --package mdebian-snmpd --rename --divert /etc/default/snmpd.backup /etc/default/snmpd
dpkg-divert --add --package mdebian-snmpd --rename --divert /etc/snmp/snmp.conf.backup /etc/snmp/snmp.conf
dpkg-divert --add --package mdebian-snmpd --rename --divert /etc/snmp/snmpd.conf.backup /etc/snmp/snmpd.conf

# Configure the SNMP service
ln -sf /etc/default/snmpd.mdebian /etc/default/snmpd
ln -sf /etc/snmp/snmp.conf.mdebian /etc/snmp/snmp.conf
ln -sf /etc/snmp/snmpd.conf.mdebian /etc/snmp/snmpd.conf

# Restart the SNMP service
systemctl restart snmpd
